name: "doxygen-install"
description: "Installs Doxygen"
inputs:
  version:
    description: "The Doxygen version to install"
    required: false
    default: "1.13.2"
runs:
  using: "composite"
  steps:
    - name: Export Doxygen version in environment
      shell: bash
      run: |
        echo "DOXYGEN_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

    - name: "Linux installation"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        wget https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        tar xzvf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        cd doxygen-${DOXYGEN_VERSION}
        sudo make install
        cd ..
        rm -rf doxygen-${DOXYGEN_VERSION}* # Clean up

    - name: "Windows installation"
      if: runner.os == 'Windows'
      shell: bash
      run: |
        mkdir doxygen-${DOXYGEN_VERSION}-windows
        cd doxygen-${DOXYGEN_VERSION}-windows
        curl -kLSs https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.windows.x64.bin.zip -o doxygen.zip
        unzip doxygen.zip
        cp * c:\\Windows
        cd ..
        rm -rf doxygen-${DOXYGEN_VERSION}-windows # Clean up

    - name: "MacOS installation"
      if: runner.os == 'MacOS'
      shell: bash
      run: |
        wget https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/Doxygen-${DOXYGEN_VERSION}.dmg
        sudo hdiutil attach Doxygen-${DOXYGEN_VERSION}.dmg
        sudo cp /Volumes/Doxygen/Doxygen.app/Contents/MacOS/Doxywizard /usr/local/bin
        sudo cp /Volumes/Doxygen/Doxygen.app/Contents/Resources/doxygen /usr/local/bin
        sudo cp /Volumes/Doxygen/Doxygen.app/Contents/Resources/doxyindexer /usr/local/bin
        sudo hdiutil detach /Volumes/Doxygen
        rm Doxygen-${DOXYGEN_VERSION}.dmg # Clean up
